
package com.emc.timeserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeServer", targetNamespace = "http://timeserver.emc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsString", targetNamespace = "http://timeserver.emc.com/", className = "com.emc.timeserver.GetTimeAsString")
    @ResponseWrapper(localName = "getTimeAsStringResponse", targetNamespace = "http://timeserver.emc.com/", className = "com.emc.timeserver.GetTimeAsStringResponse")
    @Action(input = "http://timeserver.emc.com/TimeServer/getTimeAsStringRequest", output = "http://timeserver.emc.com/TimeServer/getTimeAsStringResponse")
    public String getTimeAsString();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeFromServer", targetNamespace = "http://timeserver.emc.com/", className = "com.emc.timeserver.GetTimeFromServer")
    @ResponseWrapper(localName = "getTimeFromServerResponse", targetNamespace = "http://timeserver.emc.com/", className = "com.emc.timeserver.GetTimeFromServerResponse")
    @Action(input = "http://timeserver.emc.com/TimeServer/getTimeFromServerRequest", output = "http://timeserver.emc.com/TimeServer/getTimeFromServerResponse")
    public String getTimeFromServer();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicketFare", targetNamespace = "http://timeserver.emc.com/", className = "com.emc.timeserver.GetTicketFare")
    @ResponseWrapper(localName = "getTicketFareResponse", targetNamespace = "http://timeserver.emc.com/", className = "com.emc.timeserver.GetTicketFareResponse")
    @Action(input = "http://timeserver.emc.com/TimeServer/getTicketFareRequest", output = "http://timeserver.emc.com/TimeServer/getTicketFareResponse")
    public String getTicketFare(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
