
package com.emc.timeserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TimeServerService", targetNamespace = "urn:emc.timeserver/ws", wsdlLocation = "http://127.0.0.1:9876/nav?WSDL")
public class TimeServerService
    extends Service
{

    private final static URL TIMESERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMESERVERSERVICE_EXCEPTION;
    private final static QName TIMESERVERSERVICE_QNAME = new QName("urn:emc.timeserver/ws", "TimeServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9876/nav?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIMESERVERSERVICE_WSDL_LOCATION = url;
        TIMESERVERSERVICE_EXCEPTION = e;
    }

    public TimeServerService() {
        super(__getWsdlLocation(), TIMESERVERSERVICE_QNAME);
    }

    public TimeServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMESERVERSERVICE_QNAME, features);
    }

    public TimeServerService(URL wsdlLocation) {
        super(wsdlLocation, TIMESERVERSERVICE_QNAME);
    }

    public TimeServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMESERVERSERVICE_QNAME, features);
    }

    public TimeServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimeServer
     */
    @WebEndpoint(name = "TimeServicePort")
    public TimeServer getTimeServicePort() {
        return super.getPort(new QName("urn:emc.timeserver/ws", "TimeServicePort"), TimeServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeServer
     */
    @WebEndpoint(name = "TimeServicePort")
    public TimeServer getTimeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:emc.timeserver/ws", "TimeServicePort"), TimeServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMESERVERSERVICE_EXCEPTION!= null) {
            throw TIMESERVERSERVICE_EXCEPTION;
        }
        return TIMESERVERSERVICE_WSDL_LOCATION;
    }

}
